package storage

import (
	"bytes"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/sudiptadeb/memd/server/internal/logs"
)

// GeneratedIndexName is the per-directory auto-generated manifest file. It is
// an OKF-style index: a machine-maintained listing of a directory's direct
// children (sub-folders and files), with each file's type / title /
// description pulled from its front matter. It is regenerated on every
// mutation and must not be hand-edited — the curated, editorial index lives in
// MEMORY.md, which the indexer never touches.
const GeneratedIndexName = "index.md"

// generatedMarker is written into the body of every generated index.md so a
// human (or agent) can tell at a glance that the file is machine-owned.
const generatedMarker = "<!-- Generated by memd — do not edit. Regenerated on every change. The curated index is MEMORY.md. -->"

// IndexedBackend decorates a Backend so that every directory touched by a
// mutation (and its ancestors up to the root) gets its generated index.md
// refreshed. Reads are passed straight through; only the four mutating verbs
// trigger reindexing, and index writes go to the inner backend directly so
// they never recurse.
type IndexedBackend struct {
	Backend
}

// WrapIndexed returns b wrapped so its directories keep a generated index.md.
// A nil backend is returned unchanged.
func WrapIndexed(b Backend) Backend {
	if b == nil {
		return nil
	}
	return &IndexedBackend{Backend: b}
}

func (ib *IndexedBackend) Write(p string, content []byte, message string) error {
	if err := ib.Backend.Write(p, content, message); err != nil {
		return err
	}
	// A direct write to a generated index would loop; the inner writes below
	// bypass this method, but guard against an external caller too.
	if path.Base(p) != GeneratedIndexName {
		ib.reindexChain(dirRel(p), message)
	}
	return nil
}

func (ib *IndexedBackend) Move(src, dst, message string) error {
	if err := ib.Backend.Move(src, dst, message); err != nil {
		return err
	}
	ib.reindexChain(dirRel(dst), message)
	if dirRel(src) != dirRel(dst) {
		ib.reindexChain(dirRel(src), message)
	}
	return nil
}

func (ib *IndexedBackend) Delete(p, message string) error {
	if err := ib.Backend.Delete(p, message); err != nil {
		return err
	}
	ib.reindexChain(dirRel(p), message)
	return nil
}

func (ib *IndexedBackend) DeleteFolder(p, message string) error {
	if err := ib.Backend.DeleteFolder(p, message); err != nil {
		return err
	}
	ib.reindexChain(dirRel(p), message)
	return nil
}

// reindexChain refreshes the index for dir and every ancestor up to the root.
// A directory's index lists its sub-folders, so adding or removing a folder
// must be reflected in the parent's index too. Indexing is best-effort: the
// mutation has already succeeded, so a failure here is logged, not surfaced.
func (ib *IndexedBackend) reindexChain(dir, message string) {
	for {
		if err := ib.reindexDir(dir); err != nil {
			logs.Warn("index: regenerating %s/index.md failed: %v", dir, err)
		}
		if dir == "" {
			return
		}
		dir = dirRel(dir)
	}
}

// reindexDir rebuilds dir's index.md from its direct children and writes it
// only when the content actually changed (ignoring the server-managed memd:
// stats), so an edit that doesn't alter titles or structure produces no churn.
func (ib *IndexedBackend) reindexDir(dir string) error {
	body, ok, err := ib.renderDirIndex(dir)
	if err != nil {
		return err
	}
	indexPath := GeneratedIndexName
	if dir != "" {
		indexPath = dir + "/" + GeneratedIndexName
	}
	if !ok {
		// Nothing left to index (empty dir). Leave any existing index.md
		// alone rather than write an empty stub.
		return nil
	}
	if existing, err := ib.Backend.ReadRaw(indexPath); err == nil {
		old := ParsePage(existing)
		new := ParsePage(body)
		if bytes.Equal(old.Body, new.Body) && old.AgentFM == new.AgentFM {
			return nil // unchanged — skip to avoid write/commit churn
		}
	}
	return ib.Backend.Write(indexPath, body, "memd: refresh "+indexPath)
}

// renderDirIndex builds the OKF index.md content for dir. ok is false when the
// directory has no listable children (so there is nothing to index).
func (ib *IndexedBackend) renderDirIndex(dir string) (content []byte, ok bool, err error) {
	entries, err := ib.Backend.ListPath(dir)
	if err != nil {
		return nil, false, err
	}
	var folders []DirEntry
	var files []DirEntry
	for _, e := range entries {
		if e.IsDir {
			folders = append(folders, e)
			continue
		}
		// Skip the generated index itself; MEMORY.md is the curated index and
		// is listed but never treated as a concept.
		if e.Name == GeneratedIndexName {
			continue
		}
		files = append(files, e)
	}
	if len(folders) == 0 && len(files) == 0 {
		return nil, false, nil
	}

	title := "memory"
	if dir != "" {
		title = path.Base(dir)
	}
	var buf bytes.Buffer
	buf.WriteString("---\n")
	buf.WriteString("type: index\n")
	fmt.Fprintf(&buf, "title: %s\n", title)
	buf.WriteString("okf: generated\n")
	buf.WriteString("---\n\n")
	buf.WriteString(generatedMarker)
	buf.WriteString("\n\n")
	heading := "memory"
	if dir != "" {
		heading = dir
	}
	fmt.Fprintf(&buf, "# Index — %s\n", heading)

	if len(folders) > 0 {
		buf.WriteString("\n## Folders\n\n")
		for _, f := range folders {
			fmt.Fprintf(&buf, "- [%s/](%s/%s)\n", f.Name, f.Name, GeneratedIndexName)
		}
	}
	if len(files) > 0 {
		buf.WriteString("\n## Files\n\n")
		for _, f := range files {
			t, typ, desc := ib.pageSummary(f.Path, f.Name)
			line := fmt.Sprintf("- [%s](%s)", t, f.Name)
			if typ != "" {
				line += fmt.Sprintf(" — `%s`", typ)
			}
			if desc != "" {
				line += " — " + desc
			}
			buf.WriteString(line + "\n")
		}
	}
	return buf.Bytes(), true, nil
}

// pageSummary derives a child file's display title, OKF type, and description.
// title falls back to the first H1 in the body, then the bare filename. Reads
// go through ReadRaw so listing a directory never inflates access stats.
func (ib *IndexedBackend) pageSummary(relPath, name string) (title, typ, desc string) {
	title = name
	raw, err := ib.Backend.ReadRaw(relPath)
	if err != nil {
		return title, "", ""
	}
	if !hasManagedMetadataPath(relPath) {
		return title, "", ""
	}
	pg, _ := parseManagedPage(relPath, raw)
	fields := FieldsFromAgentFM(pg.AgentFM)
	if v := fields["title"]; v != "" {
		title = v
	} else if h1 := firstH1(pg.Body); h1 != "" {
		title = h1
	}
	return title, fields["type"], fields["description"]
}

// firstH1 returns the text of the first markdown H1 ("# ...") in body, or "".
func firstH1(body []byte) string {
	for _, line := range strings.Split(string(body), "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "# ") {
			return strings.TrimSpace(t[2:])
		}
	}
	return ""
}

// dirRel returns the parent directory of a slash path, or "" for a root-level
// path. It never returns "." so the root is always the empty string.
func dirRel(p string) string {
	p = strings.Trim(path.Clean(p), "/")
	d := path.Dir(p)
	if d == "." || d == "/" {
		return ""
	}
	return d
}

// FieldsFromAgentFM extracts top-level scalar fields (key: value) from the
// agent-managed front matter text. List- and map-valued keys are skipped;
// surrounding quotes and inline list brackets are trimmed from scalar values.
// Used by the indexer (type/title/description) and the graph builder.
func FieldsFromAgentFM(agentFM string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(agentFM, "\n") {
		if line == "" || isIndented(line) {
			continue
		}
		idx := strings.Index(line, ":")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(strings.TrimRight(line[idx+1:], "\r"))
		if key == "" || val == "" {
			continue // a key with a nested block (val empty) — not a scalar
		}
		val = strings.Trim(val, `"'`)
		out[key] = val
	}
	return out
}

var markdownLinkRE = regexp.MustCompile(`\[[^\]]*\]\(([^)\s]+)\)`)

// ExtractMarkdownLinks returns the local link targets in body: relative paths
// to other memory files. External links (http, https, mailto), pure anchors
// (#foo), and protocol-relative URLs are skipped. Any #fragment is dropped.
func ExtractMarkdownLinks(body []byte) []string {
	var out []string
	seen := map[string]bool{}
	for _, m := range markdownLinkRE.FindAllSubmatch(body, -1) {
		target := string(m[1])
		if i := strings.IndexByte(target, '#'); i >= 0 {
			target = target[:i]
		}
		target = strings.TrimSpace(target)
		if target == "" {
			continue
		}
		if strings.Contains(target, "://") || strings.HasPrefix(target, "//") ||
			strings.HasPrefix(target, "mailto:") || strings.HasPrefix(target, "#") {
			continue
		}
		if !seen[target] {
			seen[target] = true
			out = append(out, target)
		}
	}
	sort.Strings(out)
	return out
}
